"""Module for the XTB constants."""

API_MAX_CONN_TRIES = 3
API_SEND_TIMEOUT = 100
DEFAULT_XAPI_ADDRESS = "xapi.xtb.com"
DEFAULT_XAPI_PORT = 5124
DEFUALT_XAPI_STREAMING_PORT = 5125
ENCODING = "utf-8"
FILE_APPEND = "a"
FILE_READ = "r"
FILE_WRITE = "w"
LOGGER_NAME = "xtb_logger"
WRAPPER_NAME = "python"
WRAPPER_VERSION = "2.5.0"
